---
title: "Virus simulation analysis"
author: "Amicone Massimo"
date: "10/2/2021"
output: pdf_document
---

### Without Migration

```{r,load no migration}
library("writexl")

U=0.1 ##mutation rate
N=2000000
bottleneck=1/1000 ##dilution
growth=1/bottleneck ## average growth factor
L=30000 ##number of sites
input_file=paste("Virus_Evolution_N",N,"_L",L,".RData",sep="")
output_file1="U_estimate.xlsx" ##contains the mutation rates estimate from the simulated mutation frequencies
output_file2="Mutation_Frequencies.xlsx" ##contains the actual mutation frequencies at the end of the simulation
output_file3="Simulated_SFS.xlsx" ##contains the site frequency spectrum values (frequency and proportions)
load(input_file)

generations=15 ##number of passages
simulations=100
```

```{r,Estimated U}


##distribution of U
est_u=c()
for(pop in 1:simulations){
  u=Freq_all[pop+1,generations]/generations
  est_u=c(est_u,u)
}

est_u=(est_u/L)*10^6
data=data.frame(est_u)

Migration=rep("m=0",length(data))
U_est=data.frame(Migration,data)
write_xlsx(U_est,output_file1)
```

```{r,site frequency}
##site frequency spectrum
Counts=Counts_all
freq=Counts/N
freq=as.data.frame(freq)
write_xlsx(freq,output_file2)

bins=7
intervals=seq(0,0.03,length.out = bins)

a=freq
a_counts=c()
for(i in 1:(length(intervals)-1)){
  x0=intervals[i]
  x1=intervals[i+1]
  a_counts=c(a_counts,length(which(a>x0 & a<=x1)))
}

a_freq=a_counts/sum(a_counts)
d=a_freq
e=as.vector(d)

data=data.frame(e,intervals[2:(length(intervals))])
colnames(data)=c("Proportion","Frequency")

Migration=rep("m=0",dim(data)[1])
Sfs=data.frame(Migration,data)
write_xlsx(Sfs,output_file3)
```

### With Migration

```{r,load w migration}
migration=0.1
input_file=paste("Virus_Evolution_M",migration,"_N",N,"_L",L,".RData",sep="")
output_file1="U_estimate_M01.xlsx" ##contains the mutation rates estimate from the simulated mutation frequencies
output_file2="Mutation_Frequencies_M01.xlsx" ##contains the actual mutation frequencies at the end of the simulation
output_file3="Simulated_SFS_M01.xlsx" ##contains the site frequency spectrum values (frequency and proportions)
load(input_file)
```

```{r,Estimated U w migration}

##distribution of U
est_u=c()
for(pop in 1:simulations){
  u=Freq_all[pop+1,generations]/generations
  est_u=c(est_u,u)
}

est_u=(est_u/L)*10^6

Migration=rep("m=0.1",length(est_u))
data=data.frame(Migration,est_u)
U_est=rbind(U_est,data)
write_xlsx(U_est,output_file1)
```

```{r,site frequency w migration}
##site frequency spectrum
Counts=Counts_all
freq=Counts/N
freq=as.data.frame(freq)
write_xlsx(freq,output_file2)

bins=7
intervals=seq(0,0.03,length.out = bins)

a=freq
a_counts=c()
for(i in 1:(length(intervals)-1)){
  x0=intervals[i]
  x1=intervals[i+1]
  a_counts=c(a_counts,length(which(a>x0 & a<=x1)))
}

a_freq=a_counts/sum(a_counts)
d=a_freq
e=as.vector(d)

Migration=rep("m=0.1",length(e))
data=data.frame(Migration,e,intervals[2:(length(intervals))])
colnames(data)=c("Migration","Proportion","Frequency")
Sfs=rbind(Sfs,data)
write_xlsx(Sfs,output_file3)
```

